import type * as Preset from '@docusaurus/preset-classic'
import type { Config } from '@docusaurus/types'
import { themes as prismThemes } from 'prism-react-renderer'

// The ONE identity object. Defined in ./src/project.ts so the MDX components can
// import the same source (a config module cannot be imported from MDX). Every
// name reference on the site resolves from here — the rename is a one-file edit.
import { PROJECT, pkg } from './src/project'

const config: Config = {
  title: PROJECT.name,
  tagline: PROJECT.tagline,
  favicon: 'img/favicon.svg',

  url: PROJECT.pagesUrl,
  baseUrl: PROJECT.pagesBaseUrl,

  organizationName: PROJECT.org,
  projectName: PROJECT.repo,
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  // A broken link or anchor is a build failure — a hard gate (spec §2.8).
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',
  onDuplicateRoutes: 'throw',

  i18n: { defaultLocale: 'en', locales: ['en'] },

  // Expose the identity to the client so React pages read it too (no hardcoding).
  customFields: {
    project: PROJECT,
  },

  markdown: {
    mermaid: false,
    // Hand-written pages are `.mdx` (JSX components); the generated TypeDoc
    // pages are `.md` and must parse as plain CommonMark — their signatures
    // contain `<...>` generics that are not JSX. 'detect' picks per extension.
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  plugins: [
    [
      'docusaurus-plugin-typedoc',
      {
        // The generated API reference for @timbre/player — every index.ts
        // export rendered from its real TSDoc. This is the mechanism that makes
        // "nothing missed" provable (spec §2.1).
        id: 'player-api',
        entryPoints: ['../packages/player/src/index.ts'],
        tsconfig: '../packages/player/tsconfig.json',
        out: 'docs/api/player',
        readme: 'none',
        // One file per exported member — the coverage check diffs these against
        // index.ts, and the sidebar browses them by kind.
        outputFileStrategy: 'members',
        entryFileName: 'index.md',
        fileExtension: '.md',
        // Clean, signature-first rendering.
        useCodeBlocks: true,
        expandObjects: true,
        expandParameters: true,
        // Parameters render as a clean table (they are not anchor-linked).
        parametersFormat: 'table',
        // Members that ARE cross-referenced by anchor (`#gaindb`, `#volume`)
        // must be headings so the anchor exists — tables have no per-row id, and
        // a link to one is a dead anchor (a hard gate). Lists give each a real
        // heading id that Docusaurus's slug matches.
        propertiesFormat: 'list',
        enumMembersFormat: 'list',
        typeDeclarationFormat: 'list',
        indexFormat: 'table',
        hidePageHeader: true,
        hideBreadcrumbs: true,
        // Docusaurus reads this folder with an autogenerated sidebar.
        sidebar: { autoConfiguration: true, pretty: true },
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          editUrl: `${PROJECT.repoUrl}/tree/main/website/`,
          breadcrumbs: true,
          showLastUpdateTime: false,
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      defaultMode: 'light',
      respectPrefersColorScheme: true,
    },
    docs: {
      sidebar: { hideable: true, autoCollapseCategories: true },
    },
    navbar: {
      title: PROJECT.name,
      hideOnScroll: false,
      items: [
        { to: '/docs/intro', label: 'Docs', position: 'left' },
        { to: '/docs/guides/music-player', label: 'Guides', position: 'left' },
        { to: '/docs/concepts/position-anchor', label: 'Concepts', position: 'left' },
        { to: '/docs/api/player/', label: 'API', position: 'left' },
        {
          href: PROJECT.repoUrl,
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'light',
      links: [
        {
          title: 'Docs',
          items: [
            { label: 'Getting started', to: '/docs/intro' },
            { label: 'Music-player guide', to: '/docs/guides/music-player' },
            { label: 'API reference', to: '/docs/api/player/' },
          ],
        },
        {
          title: 'Concepts',
          items: [
            { label: 'Position anchor', to: '/docs/concepts/position-anchor' },
          ],
        },
        {
          title: 'More',
          items: [{ label: 'GitHub', href: PROJECT.repoUrl }],
        },
      ],
      copyright: `${pkg('player')} · built on libmpv · MIT`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.vsDark,
      additionalLanguages: ['bash', 'json', 'diff'],
    },
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 3,
    },
  } satisfies Preset.ThemeConfig,
}

export default config
