import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Two sidebars: the hand-written docs (getting started, guides, concepts) and
 * the fully generated API reference. The API tree is autogenerated from the
 * folder `docusaurus-plugin-typedoc` writes into, so a new export appears in the
 * nav with no edit here.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['guides/music-player'],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: ['concepts/position-anchor'],
    },
    {
      type: 'category',
      label: 'API reference',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
}

export default sidebars
